<a href="https://colab.research.google.com/github/gomlfx/ApiaryFund/blob/master/eurusd_automl_hist_range.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install flaml

In [8]:
#designed for Jupyter/kaggle/colab
import pandas as pd
import numpy as np
#import matplotlib for plotting 
import matplotlib.pyplot as plt
%matplotlib inline
#import normalization
from sklearn import preprocessing
import xgboost as xg
from sklearn.ensemble import RandomForestRegressor as rf
#import auto hyperparameter tuning
from flaml import AutoML
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from lightgbm import LGBMRegressor


In [9]:
 #MT4 csv 
df1=pd.read_csv('EURUSD1440.csv', names=['d','t','eu_o','eu_h','eu_l','eu_c','eu_v'])
df_m_5 = df1.tail(2000)
df2 = df1.tail(2000)
# df2=pd.read_csv('GBPUSD1440.csv', names=['d','t','gu_o','gu_h','gu_l','gu_c','gu_v'])
# df2 = df2.tail(2000)

# df3=pd.read_csv('USDCAD1440.csv', names=['d','t','uc_o','uc_h','uc_l','uc_c','uc_v'])
# df3 = df3.tail(2000)

# df4=pd.read_csv('USDCHF1440.csv', names=['d','t','uf_o','uf_h','uf_l','uf_c','uf_v'])
# df4 = df4.tail(2000)

# df5=pd.read_csv('USDJPY1440.csv', names=['d','t','uj_o','uj_h','uj_l','uj_c','uj_v'])
# df5 = df5.tail(2000)

# df6=pd.read_csv('USDSEK1440.csv', names=['d','t','us_o','us_h','us_l','us_c','us_v'])
# df6 = df6.tail(2000)

# #using merge
# df_m_1 = df1.merge(df2, on='d')
# df_m_2 = df_m_1.merge(df3, on='d')
# df_m_3 = df_m_2.merge(df4, on='d')
# df_m_4 = df_m_3.merge(df5, on='d')
# df_m_5 = df_m_4.merge(df6, on='d')
# df_m_5 = df_m_5.drop(columns='t_x')
# df_m_5 = df_m_5.drop(columns='t_y')

# pd.set_option('display.max_columns', None)
# print(df_m_5) 

In [10]:
df2.tail()

d      t     eu_o     eu_h     eu_l     eu_c   eu_v
12785  2021.12.07  00:00  1.12821  1.12982  1.12273  1.12681  78783
12786  2021.12.08  00:00  1.12650  1.13547  1.12627  1.13418  85355
12787  2021.12.09  00:00  1.13422  1.13452  1.12782  1.12924  71564
12788  2021.12.10  00:00  1.12913  1.13239  1.12650  1.13165  76961
12789  2021.12.13  00:00  1.13106  1.13191  1.12920  1.12960   7970

In [11]:

# #2 days forward
# df_m_5['eu_High_next_day2'] = df_m_5['eu_h'].shift(-2)
# df_m_5['eu_Low_next_day2'] = df_m_5['eu_l'].shift(-2)
# df_m_5['eu_Close_next_day2'] = df_m_5['eu_c'].shift(-2) 
# #3 days forward
# df_m_5['eu_High_next_day3'] = df_m_5['eu_h'].shift(-3)
# df_m_5['eu_Low_next_day3'] = df_m_5['eu_l'].shift(-3)
# df_m_5['eu_Close_next_day3'] = df_m_5['eu_c'].shift(-3) 
# #4 days forward 
# df_m_5['eu_High_next_day4'] = df_m_5['eu_h'].shift(-4)
# df_m_5['eu_Low_next_day4'] = df_m_5['eu_l'].shift(-4)
# df_m_5['eu_Close_next_day4'] = df_m_5['eu_c'].shift(-4) 
# #5 days forward
# df_m_5['eu_High_next_day5'] = df_m_5['eu_h'].shift(-5)
# df_m_5['eu_Low_next_day5'] = df_m_5['eu_l'].shift(-5)
# df_m_5['eu_Close_next_day5'] = df_m_5['eu_c'].shift(-5) 

#Features
#1 day ago (features)
df_m_5['eu_High_last_day1'] = df_m_5['eu_h'].shift(1)
df_m_5['eu_Low_last_day1'] = df_m_5['eu_l'].shift(1)
df_m_5['eu_Close_last_day1'] = df_m_5['eu_c'].shift(1) 
#2 days ago
df_m_5['eu_High_last_day2'] = df_m_5['eu_h'].shift(2)
df_m_5['eu_Low_last_day2'] = df_m_5['eu_l'].shift(2)
df_m_5['eu_Close_last_day2'] = df_m_5['eu_c'].shift(2) 
#3 days ago
df_m_5['eu_High_last_day3'] = df_m_5['eu_h'].shift(3)
df_m_5['eu_Low_last_day3'] = df_m_5['eu_l'].shift(3)
df_m_5['eu_Close_last_day3'] = df_m_5['eu_c'].shift(3) 
#4 days ago 
df_m_5['eu_High_last_day4'] = df_m_5['eu_h'].shift(4)
df_m_5['eu_Low_last_day4'] = df_m_5['eu_l'].shift(4)
df_m_5['eu_Close_last_day4'] = df_m_5['eu_c'].shift(4) 
#5 days ago
df_m_5['eu_High_last_day5'] = df_m_5['eu_h'].shift(5)
df_m_5['eu_Low_last_day5'] = df_m_5['eu_l'].shift(5)
df_m_5['eu_Close_last_day5'] = df_m_5['eu_c'].shift(5) 
#1 day ago (features)
df_m_5['eu_High_last_day6'] = df_m_5['eu_h'].shift(6)
df_m_5['eu_Low_last_day6'] = df_m_5['eu_l'].shift(6)
df_m_5['eu_Close_last_day6'] = df_m_5['eu_c'].shift(6) 
#2 days ago
df_m_5['eu_High_last_day7'] = df_m_5['eu_h'].shift(7)
df_m_5['eu_Low_last_day7'] = df_m_5['eu_l'].shift(7)
df_m_5['eu_Close_last_day7'] = df_m_5['eu_c'].shift(7) 
#3 days ago
df_m_5['eu_High_last_day8'] = df_m_5['eu_h'].shift(8)
df_m_5['eu_Low_last_day8'] = df_m_5['eu_l'].shift(8)
df_m_5['eu_Close_last_day8'] = df_m_5['eu_c'].shift(8) 
#4 days ago 
df_m_5['eu_High_last_day9'] = df_m_5['eu_h'].shift(9)
df_m_5['eu_Low_last_day9'] = df_m_5['eu_l'].shift(9)
df_m_5['eu_Close_last_day9'] = df_m_5['eu_c'].shift(9) 
#5 days ago
df_m_5['eu_High_last_day10'] = df_m_5['eu_h'].shift(10)
df_m_5['eu_Low_last_day10'] = df_m_5['eu_l'].shift(10)
df_m_5['eu_Close_last_day10'] = df_m_5['eu_c'].shift(10) 

#Target
#1 day forward 
df_m_5['eu_High_next_day1'] = df_m_5['eu_h'].shift(-1)
df_m_5['eu_Low_next_day1'] = df_m_5['eu_l'].shift(-1)
df_m_5['eu_Close_next_day1'] = df_m_5['eu_c'].shift(-1) 

#drop null and useless columns
df_m_5 = df_m_5.dropna()
df_m_5 = df_m_5.drop(['t','eu_v'], axis=1)



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stab

In [12]:
df_m_5 

d     eu_o  ...  eu_Low_next_day1  eu_Close_next_day1
10800  2014.04.11  1.38868  ...           1.38080             1.38181
10801  2014.04.14  1.38573  ...           1.37899             1.38133
10802  2014.04.15  1.38185  ...           1.38035             1.38160
10803  2014.04.16  1.38133  ...           1.38109             1.38131
10804  2014.04.17  1.38160  ...           1.38068             1.38068
...           ...      ...  ...               ...                 ...
12784  2021.12.06  1.12997  ...           1.12273             1.12681
12785  2021.12.07  1.12821  ...           1.12627             1.13418
12786  2021.12.08  1.12650  ...           1.12782             1.12924
12787  2021.12.09  1.13422  ...           1.12650             1.13165
12788  2021.12.10  1.12913  ...           1.12920             1.12960

[1989 rows x 38 columns]

In [13]:
df_m_5.insert(1,'index',df_m_5.index)

In [ ]:
# #new column: high vs low
# df_m_5['eu_h_or_l'] = ((df_m_5.eu_h - df_m_5.eu_o) > (df_m_5.eu_o - df_m_5.eu_l)) 
# df_m_5.eu_h_or_l = df_m_5.eu_h_or_l.replace({True:1,False:0})

# #new column: close vs yesterday
# df_m_5['eu_c_vs_c'] = (df_m_5.eu_c > df_m_5.eu_o) 
# df_m_5.eu_c_vs_c = df_m_5.eu_c_vs_c.replace({True:1,False:0})

# #new column: shift tomorrow to today
# df_m_5['eu_High_next_day'] = df_m_5['eu_h'].shift(-1)
# df_m_5['eu_Low_next_day'] = df_m_5['eu_l'].shift(-1)
# df_m_5['eu_Close_next_day'] = df_m_5['eu_c'].shift(-1)
# df_m_5 = df_m_5.dropna()


In [14]:
df_m_5.tail()

d  index  ...  eu_Low_next_day1  eu_Close_next_day1
12784  2021.12.06  12784  ...           1.12273             1.12681
12785  2021.12.07  12785  ...           1.12627             1.13418
12786  2021.12.08  12786  ...           1.12782             1.12924
12787  2021.12.09  12787  ...           1.12650             1.13165
12788  2021.12.10  12788  ...           1.12920             1.12960

[5 rows x 39 columns]

In [15]:

df_m_5.isna().sum()

d                      0
index                  0
eu_o                   0
eu_h                   0
eu_l                   0
eu_c                   0
eu_High_last_day1      0
eu_Low_last_day1       0
eu_Close_last_day1     0
eu_High_last_day2      0
eu_Low_last_day2       0
eu_Close_last_day2     0
eu_High_last_day3      0
eu_Low_last_day3       0
eu_Close_last_day3     0
eu_High_last_day4      0
eu_Low_last_day4       0
eu_Close_last_day4     0
eu_High_last_day5      0
eu_Low_last_day5       0
eu_Close_last_day5     0
eu_High_last_day6      0
eu_Low_last_day6       0
eu_Close_last_day6     0
eu_High_last_day7      0
eu_Low_last_day7       0
eu_Close_last_day7     0
eu_High_last_day8      0
eu_Low_last_day8       0
eu_Close_last_day8     0
eu_High_last_day9      0
eu_Low_last_day9       0
eu_Close_last_day9     0
eu_High_last_day10     0
eu_Low_last_day10      0
eu_Close_last_day10    0
eu_High_next_day1      0
eu_Low_next_day1       0
eu_Close_next_day1     0
dtype: int64

In [16]:
df_m_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1989 entries, 10800 to 12788
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   d                    1989 non-null   object 
 1   index                1989 non-null   int64  
 2   eu_o                 1989 non-null   float64
 3   eu_h                 1989 non-null   float64
 4   eu_l                 1989 non-null   float64
 5   eu_c                 1989 non-null   float64
 6   eu_High_last_day1    1989 non-null   float64
 7   eu_Low_last_day1     1989 non-null   float64
 8   eu_Close_last_day1   1989 non-null   float64
 9   eu_High_last_day2    1989 non-null   float64
 10  eu_Low_last_day2     1989 non-null   float64
 11  eu_Close_last_day2   1989 non-null   float64
 12  eu_High_last_day3    1989 non-null   float64
 13  eu_Low_last_day3     1989 non-null   float64
 14  eu_Close_last_day3   1989 non-null   float64
 15  eu_High_last_day4    1989 non-nul

In [17]:
#extract row for variable
last_row = df_m_5.iloc[-1:,np.r_[2:36]].values
print(last_row) 

[[1.12913 1.13239 1.1265  1.13165 1.13452 1.12782 1.12924 1.13547 1.12627
  1.13418 1.12982 1.12273 1.12681 1.13109 1.12664 1.12848 1.13333 1.12665
  1.13088 1.13475 1.12952 1.13013 1.13594 1.13023 1.1319  1.13827 1.1235
  1.1339  1.13117 1.12582 1.12918 1.13295 1.12051 1.13177]]


In [18]:
#for high prediction
#select rows to use for x,y
x_h = df_m_5.iloc[:,np.r_[2:36]].values
print(x_h)
y_h = df_m_5.iloc[:,[36]].values
print(y_h) 

[[1.38868 1.39057 1.38632 ... 1.37729 1.37047 1.37513]
 [1.38573 1.38627 1.3808  ... 1.38085 1.37215 1.37735]
 [1.38185 1.38332 1.37899 ... 1.38152 1.3769  1.37932]
 ...
 [1.1265  1.13547 1.12627 ... 1.12551 1.11859 1.12   ]
 [1.13422 1.13452 1.12782 ... 1.12295 1.11959 1.12062]
 [1.12913 1.13239 1.1265  ... 1.13295 1.12051 1.13177]]
[[1.38627]
 [1.38332]
 [1.38507]
 ...
 [1.13452]
 [1.13239]
 [1.13191]]


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_h, y_h, test_size = 0.30)

In [20]:
automl_reg = AutoML()
automl_reg.fit(X_train, y_train, estimator_list="auto", task="regression", time_budget=None, eval_method="auto", n_jobs=-1)

[flaml.automl: 12-13 05:11:35] {1943} INFO - task = regression
[flaml.automl: 12-13 05:11:35] {1945} INFO - Data split method: uniform
[flaml.automl: 12-13 05:11:35] {1949} INFO - Evaluation method: cv
[flaml.automl: 12-13 05:11:35] {2019} INFO - Minimizing error metric: 1-r2
[flaml.automl: 12-13 05:11:35] {2071} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth']
[flaml.automl: 12-13 05:11:35] {2311} INFO - iteration 0, current learner lgbm
[flaml.automl: 12-13 05:11:35] {2425} INFO - Estimated sufficient time budget=784s. Estimated necessary time budget=6s.
[flaml.automl: 12-13 05:11:35] {2505} INFO -  at 0.1s,	estimator lgbm's best error=0.4813,	best estimator lgbm's best error=0.4813
[flaml.automl: 12-13 05:11:35] {2311} INFO - iteration 1, current learner lgbm
[flaml.automl: 12-13 05:11:35] {2505} INFO -  at 0.2s,	estimator lgbm's best error=0.4813,	best estimator lgbm's best error=0.4813
[flaml.automl: 12-13 05:11:35] {2311} INFO - 

In [21]:
#paste retrained model
sugg_reg_high_param = RandomForestRegressor(max_features=0.7153649632061108, max_leaf_nodes=252,
                      n_estimators=47, n_jobs=-1)
#paste finished
sugg_reg_high_param.fit(X_train,y_train)
y_pred_h=sugg_reg_high_param.predict(last_row)
y_pred_h

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


array([1.13363275])

In [22]:
y_pred = sugg_reg_high_param.predict(X_test)

In [23]:
def mean_absolute_percentage_error(y_true,y_pred):
  y_true, y_pred = np.array(y_true), np.array(y_pred)
  return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape = mean_absolute_percentage_error(y_test,y_pred)

In [24]:
#for regression score
from sklearn import metrics 
print('MAE:', metrics.mean_absolute_error(y_test,y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('MAPE:', mape)
print('MedAE', metrics.median_absolute_error(y_test,y_pred)) 

MAE: 0.003000246367091531
MSE: 1.921056714198677e-05
RMSE: 0.004382986098767228
MAPE: 6.22102559115412
MedAE 0.002337077577859503


In [25]:
#for low prediction
#select rows to use for x,y
x_l = df_m_5.iloc[:,np.r_[2:36]].values
print(x_l)
y_l = df_m_5.iloc[:,[37]].values
print(y_l) 

[[1.38868 1.39057 1.38632 ... 1.37729 1.37047 1.37513]
 [1.38573 1.38627 1.3808  ... 1.38085 1.37215 1.37735]
 [1.38185 1.38332 1.37899 ... 1.38152 1.3769  1.37932]
 ...
 [1.1265  1.13547 1.12627 ... 1.12551 1.11859 1.12   ]
 [1.13422 1.13452 1.12782 ... 1.12295 1.11959 1.12062]
 [1.12913 1.13239 1.1265  ... 1.13295 1.12051 1.13177]]
[[1.3808 ]
 [1.37899]
 [1.38035]
 ...
 [1.12782]
 [1.1265 ]
 [1.1292 ]]


In [26]:
#for low prediction
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_l, y_l, test_size = 0.30)

In [27]:
automl_reg = AutoML()
automl_reg.fit(X_train, y_train, estimator_list="auto", task="regression", time_budget=None, eval_method="auto", n_jobs=-1)

[flaml.automl: 12-13 05:15:36] {1943} INFO - task = regression
[flaml.automl: 12-13 05:15:36] {1945} INFO - Data split method: uniform
[flaml.automl: 12-13 05:15:36] {1949} INFO - Evaluation method: cv
[flaml.automl: 12-13 05:15:36] {2019} INFO - Minimizing error metric: 1-r2
[flaml.automl: 12-13 05:15:36] {2071} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth']
[flaml.automl: 12-13 05:15:36] {2311} INFO - iteration 0, current learner lgbm
[flaml.automl: 12-13 05:15:36] {2425} INFO - Estimated sufficient time budget=741s. Estimated necessary time budget=5s.
[flaml.automl: 12-13 05:15:36] {2505} INFO -  at 0.1s,	estimator lgbm's best error=0.4815,	best estimator lgbm's best error=0.4815
[flaml.automl: 12-13 05:15:36] {2311} INFO - iteration 1, current learner lgbm
[flaml.automl: 12-13 05:15:36] {2505} INFO -  at 0.2s,	estimator lgbm's best error=0.4815,	best estimator lgbm's best error=0.4815
[flaml.automl: 12-13 05:15:36] {2311} INFO - 

In [28]:
#paste retrained model
sugg_reg_low_param = RandomForestRegressor(max_features=0.6347607006852164, max_leaf_nodes=166,
                      n_estimators=109, n_jobs=-1)
#paste finished
sugg_reg_low_param.fit(X_train,y_train)
y_pred_l=sugg_reg_low_param.predict(last_row)
y_pred_l

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


array([1.12903057])

In [29]:
#for low pred 
y_pred = sugg_reg_low_param.predict(X_test)
mape = mean_absolute_percentage_error(y_test,y_pred)

In [30]:
#for low pred regression score
from sklearn import metrics 
print('MAE:', metrics.mean_absolute_error(y_test,y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('MAPE:', mape)
print('MedAE', metrics.median_absolute_error(y_test,y_pred)) 

MAE: 0.002857922938228507
MSE: 1.5177321694140943e-05
RMSE: 0.003895808220913979
MAPE: 6.20847915428511
MedAE 0.002223197048358383


In [31]:
#for close prediction
#select rows to use for x,y
x_c = df_m_5.iloc[:,np.r_[2:36]].values
print(x_c)
y_c = df_m_5.iloc[:,[38]].values
print(y_c) 

[[1.38868 1.39057 1.38632 ... 1.37729 1.37047 1.37513]
 [1.38573 1.38627 1.3808  ... 1.38085 1.37215 1.37735]
 [1.38185 1.38332 1.37899 ... 1.38152 1.3769  1.37932]
 ...
 [1.1265  1.13547 1.12627 ... 1.12551 1.11859 1.12   ]
 [1.13422 1.13452 1.12782 ... 1.12295 1.11959 1.12062]
 [1.12913 1.13239 1.1265  ... 1.13295 1.12051 1.13177]]
[[1.38181]
 [1.38133]
 [1.3816 ]
 ...
 [1.12924]
 [1.13165]
 [1.1296 ]]


In [32]:
#for close prediction
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_c, y_c, test_size = 0.30)

In [33]:
automl_reg = AutoML()
automl_reg.fit(X_train, y_train, estimator_list="auto", task="regression", time_budget=None, eval_method="auto")

[flaml.automl: 12-13 05:17:21] {1943} INFO - task = regression
[flaml.automl: 12-13 05:17:21] {1945} INFO - Data split method: uniform
[flaml.automl: 12-13 05:17:21] {1949} INFO - Evaluation method: cv
[flaml.automl: 12-13 05:17:21] {2019} INFO - Minimizing error metric: 1-r2
[flaml.automl: 12-13 05:17:21] {2071} INFO - List of ML learners in AutoML Run: ['lgbm', 'rf', 'xgboost', 'extra_tree', 'xgb_limitdepth']
[flaml.automl: 12-13 05:17:21] {2311} INFO - iteration 0, current learner lgbm
[flaml.automl: 12-13 05:17:21] {2425} INFO - Estimated sufficient time budget=760s. Estimated necessary time budget=5s.
[flaml.automl: 12-13 05:17:21] {2505} INFO -  at 0.1s,	estimator lgbm's best error=0.4849,	best estimator lgbm's best error=0.4849
[flaml.automl: 12-13 05:17:21] {2311} INFO - iteration 1, current learner lgbm
[flaml.automl: 12-13 05:17:21] {2505} INFO -  at 0.2s,	estimator lgbm's best error=0.4849,	best estimator lgbm's best error=0.4849
[flaml.automl: 12-13 05:17:21] {2311} INFO - 

In [34]:
#paste retrained model
sugg_reg_close_param = RandomForestRegressor(max_features=0.5520984120275062, max_leaf_nodes=158,
                      n_estimators=103, n_jobs=-1)
#paste finished
sugg_reg_close_param.fit(X_train,y_train)
y_pred_c=sugg_reg_close_param.predict(last_row)
y_pred_c

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


array([1.13085623])

In [35]:
#for close prediction
y_pred = sugg_reg_close_param.predict(X_test)
mape = mean_absolute_percentage_error(y_test,y_pred)

In [36]:
#for close regression score
from sklearn import metrics 
print('MAE:', metrics.mean_absolute_error(y_test,y_pred))
print('MSE:', metrics.mean_squared_error(y_test, y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('MAPE:', mape)
print('MedAE', metrics.median_absolute_error(y_test,y_pred)) 
#print('MdAPE', metrics)

MAE: 0.004513143399275847
MSE: 3.631064554320328e-05
RMSE: 0.0060258315229687
MAPE: 6.373627615870056
MedAE 0.0034117639725095295


In [37]:
print('Today the predictions are:')
print('high', y_pred_h)
print('close', y_pred_c)
print('low', y_pred_l)
print('Best used as polarities.')

Today the predictions are:
high [1.13363275]
close [1.13085623]
low [1.12903057]
Best used as polarities.
